alfonsojack/whats-cookin

dist/bundle.js
dist/index.html
dist/styles.css
src/styles.css

- Initial styling for page
- centered the body
-styled the title
-styled the input box
-styled the nav bar
- added a few images with titles based on the recipes.js
-commented out alert in bundles.js
- [ X] I have performed a self-review of my code

Page layout/feature/zm

---

test/scriptsTests.js
test/testData.js
test/untestedFunctions.js

I've added a sample data sets for testing, created 3 test functions, and wrote & passed tests for them
- I added date to our testData file, ingredient data and recipe data
- I added a function to filter recipes by tag and tested it twice
- I added a function to filter recipes by name and tested it 
- I added a function to filter ingredient names of a specific recipe and tested it twice

Filter recipe lists/feature/ja

---

src/data/recipes.js
src/domUpdates.js
src/scripts.js

Fixed Bug
- exported RenderRecipes from domUpdates.js
- exported recipeData array from recipeData.js

Fix Bug: Render recipes and names to the page on load

---

dist/index.html
src/scripts.js

- Create event listener and functionality for clicking and filtering by tags
-add event listeners and event targeting to target tags and output their id
-add function to run targeted id through my filterbytag function and then run THAT output through the display recipe function
-compressed the tags on our nav bar to eliminate redunndancies

Add functionality to filter recipe by tag when tags are clicked

---

dist/index.html
src/domUpdates.js
src/scripts.js

Added display recipes function.
- Created displayRecipes function which will show the searched recipe if its typed in word for word to the search field
- Added searchField querySelector to capture the input of the search field
- [ x] I have performed a self-review of my code

Add display recipes function

---

dist/index.html
src/domUpdates.js
src/scripts.js
src/styles.css

Add all recipes button 
- add an all recipes nav to the html
- add event listener that makes that new all recipes button trigger the display all recipes functionality
- [ x] I have performed a self-review of my code

All recipes button/feature/ja

---

src/domUpdates.js
src/scripts.js
src/styles.css
test/untestedFunctions.js

- Create event listeners to make the recipe cards clickable and then create functionality to style those elements and make them produce a pop up screen populated with recipe details
- created event listeners for the recipe cards
- created language to style those recipe cards after they are put into the dom by previous event listeners
- created functionality to take IDs from those cards and use those IDs to create pop up

View recipe button/feature/ja

---

dist/index.html
src/domUpdates.js
src/scripts.js
src/styles.css

- Create and style Saved Recipes button
- deleted commented out code
- created Saved Recipes button in index.html file
- added the class to the appropriate css rules

Saved recipes button/feauture/zm

---

dist/index.html
src/data/users.js
src/domUpdates.js
src/scripts.js
src/styles.css

- Iteration 2 other than the delete save functionality. There is a condition I want to add that only allows users to save a recipe once
-add functionality to add recipesToCook key to all User object
-add functionality to select randomUser at page load
- add functionality to save recipes to randomUser
- add functionality to view saved recipes
- add functionality to filter saved recipes by tag and name
- add functionality to toggle between saved and all recipes
- edited styling to make all of this functionality make sense visually

Save recipe to cook/feature/ja

---

src/apiCalls.js
src/scripts.js

- Started api Calls
- fetchUsers function
- code is still broke

Start the api call functions

---

src/apiCalls.js
src/scripts.js

- fixed api call to nest functions within it
- fetchUsers function fixed
- fixed code

Pass API users through a function

---

src/apiCalls.js
src/scripts.js

Description
Fetch call for recipes data is built and is passed through the scripts.js via the page load event listener, the fetch returns a newly built function to define a global variable in the scripts page based on the fetched data
Changes Made
fetchRecipes function,
new functionality on scripts page creates a global variable
I have performed a self-review of my code
If it is a core feature, I have added thorough tests.

Fetch recipes API data and pass it through scripts functions

---

src/apiCalls.js
src/domUpdates.js
src/scripts.js
src/styles.css

Description
Fetch call for recipes data is built and is passed through the scripts.js via the page load event listener, the fetch returns a newly built function to define a global variable in the scripts page based on the fetched data
Changes Made
fetchRecipes function,
new functionality on scripts page creates a global variable
I have performed a self-review of my code
If it is a core feature, I have added thorough tests.

Fetch and pass ingredients api/feature/ja

---

dist/index.html
src/apiCalls.js
src/domUpdates.js
src/scripts.js

- Create functionality to delete saved recipes
- delete save recipes

Add delete save button

---

dist/index.html
src/domUpdates.js

Restyle buttons, create message for no search results, change "all" to "all categories
- refactor displayRecipes functions
- restyle buttons
- [ x] I have performed a self-review of my code

Restyle search/fix/ja

---

test/scriptsTests.js

Add extra testing to my functions
-add testing
- [ x] I have performed a self-review of my code

Add testing to scriptsTest

---

dist/index.html
src/apiCalls.js
src/domUpdates.js
src/scripts.js
src/styles.css
test/ingredients-test.js
test/recipes-tests.js

- Fixed all comments from Scott outside of testing
- moved styling out of scripts.js
- added .catch error handling for our fetch
- added title to featured recipes section
- [x ] I have performed a self-review of my code

API sad paths/feature/ja

---

dist/index.html
src/apiCalls.js
src/domUpdates.js
src/scripts.js
src/styles.css

added POST call with error handling to avoid duplicate saves. added tabs and alts to elements to raise lighthouse accessibility score to 100
- POST calls 
- Tabs
- Alt attributes on img elements
- [x ] I have performed a self-review of my code

Tab index/feature/ja

---

dist/index.html
src/apiCalls.js
src/domUpdates.js
src/ingredient-functions.js
src/recipe-functions.js
src/scripts.js
src/styles.css
test/ingredients-test.js
test/recipes-tests.js

Finished all iterations, fixed all bugs, and addressed all comments from Scott. 
-DRY up testing environment with beforeEach and variables
- add to testing, 23 passed tests with sad path testing for each function
- greet user on page load
- fix POST and add functionality to make it work on DOM
- made HTML semantic so that there are no content-bearing divs
- fixed search function so that the function doesn't trigger if there is no content in the search bar
- restyled buttons so that they move a little when active
- [x ] I have performed a self-review of my code

Semantic html/fix/ja

---

README.md
src/domUpdates.js
src/ingredient-functions.js
src/recipe-functions.js
src/scripts.js

- Complete README.md file and ensure some of the files are following the Turing Styling Guide
- README.md completed
- domUpdates.js scripts.js and recipe-functions.js and ingredients-functions.js files edited to -follow the Turing Styling Guide

Readme and edits/feature/zm

---

dist/index.html

- Changed order of categories links
- Categories links order was changed to Breakfast, Snack, Dinner, Salad, Sauce

Change categories order/feature/zm
